name: 'CI/CD'
on:
    push:
        branches:
            - main
        tags:
            - '*'
jobs:
    build-deploy:
        name: 'Build, Lint, Test, and Deploy'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              name: 'Checkout'

            - uses: actions/setup-node@v4
              name: 'Setup Node'
              with:
                  node-version: '21'
                  cache: 'npm'

            - run: npm install
              name: 'Install dependencies'

            - name: Decrypt sensitive files
              run: |
                  gpg -d --passphrase "${{ secrets.WEB_EXTENSION_GPG_PASSPHRASE }}" --batch ./app/config.ts.asc > ./app/config.ts

            - name: 'Set default env.RELEASE_VERSION'
              run: echo "RELEASE_VERSION=1.0.0" >> $GITHUB_ENV

            - name: 'Set env.RELEASE_VERSION from tag'
              if: startsWith( github.ref, 'refs/tags/')
              run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

            - name: 'Install jq'
              if: startsWith( github.ref, 'refs/tags/')
              run: brew install jq

            - name: 'Set manifest version'
              if: startsWith( github.ref, 'refs/tags/')
              run: |
                  echo $(cat ./app/manifest.json | jq '.version = "${{ env.RELEASE_VERSION}}"' ./app/manifest.json) > ./app/manifest.json

            - name: 'Commit manifest.json'
              if: startsWith( github.ref, 'refs/tags/')
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: app/manifest.json
                  commit-msg: 'Update manfiest.json version to ${{ env.RELEASE_VERSION}}'
                  github-token: ${{ secrets.SECRET_GITHUB_TOKEN }}

            - run: npm run check:formatting
              name: 'Check formatting'

            - run: npm run check:linting
              name: 'Check linting'

            - run: npm run test:unit
              name: 'Run unit tests'

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4

            - run: npm run build:firefox
              name: 'Build Firefox'

            - name: Package Firefox Extension
              run: |
                  mkdir -p ./packages
                  cd ./dist/firefox
                  zip -r ../../packages/skiptro-web.v${{env.RELEASE_VERSION}}.firefox.xpi.zip ./*
                  ls -lh ../../packages/

            - uses: actions/upload-artifact@v4
              name: 'Upload Firefox Extension to Github Actions'
              with:
                  name: Firefox Extension
                  path: packages/skiptro-web.v${{ env.RELEASE_VERSION }}.firefox.xpi.zip

            # - run: npm run build:edge
            #   name: "Build Edge"

            # - run: npm run build:chrome
            #   name: "Build Chrome"

            # - run: npm run build:opera
            #   name: "Build Opera"

            # - name: "Upload to Firefox add-on market"
            #   if: startsWith( github.ref, 'refs/tags/')
            #   uses: trmcnvn/firefox-addon@v1
            #   with:
            #     uuid: '{7069c89a-e845-4505-9f90-9dfffe9ef0d7}'
            #     xpi: packages/azure-devops-link-copy-web-ext.v${{ env.RELEASE_VERSION }}.firefox.xpi.zip
            #     manifest: dist/firefox/manifest.json
            #     api-key: ${{ secrets.FIREFOX_API_KEY }}
            #     api-secret: ${{ secrets.FIREFOX_API_SECRET }}
